# Generated by Django 4.1.7 on 2023-03-22 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_tag_alter_article_options_scope'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tag',
            new_name='name',
        ),
        migrations.AddField(
            model_name='article',
            name='tegs',
            field=models.ManyToManyField(related_name='articles', to='articles.tag'),
        ),
    ]
